---
name: Tado Proxy
version: "latest"
slug: tadoproxy
description: "Tado API Proxy for Home Assistant"
url: "https://github.com/s1adem4n/tado-api-proxy"
arch: 
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
stage: stable
legacy: false
init: false
host_network: true
panel_icon: mdi:ev-station

image: ghcr.io/s1adem4n/tado-api-proxy

options:
  email: you@email.com
  password: yourpassword

schema:
  email: str
  password: str
environment:
  - COOKIE_FILE=/data/cookies.json
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Tado Proxy API"

map:
  - config:rw
  - share:rw
